// Error Handling- try and catch :
setTimeout(() => {
    console.log("Hacking WiFi .........Please Wait")
}, 1000);

try{
    // setTimeout(() => {
    //     console.log("Error Says : I am coming Bro")
    // }, 100);
    console.log(Rohal) //Try & Catch works synchronously...
}                      
catch(error){
    console.log( " OMG "  + error);
}

setTimeout(() => {
    console.log("Fetching username and password ......Please Wait")
}, 2000);

setTimeout(() => {
    console.log("Hacking Rohal FaceBook Id ...... Please wait")
}, 3000);

setTimeout(() => {
    console.log("Username and password of Rohal (+993331855)is fetched.......PLZ Wait")
}, 4000);